<?php

/**
 * BasemrGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $medium
 * @property integer $year
 * @property string $platform
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method string      getName()     Returns the current record's "name" value
 * @method string      getMedium()   Returns the current record's "medium" value
 * @method integer     getYear()     Returns the current record's "year" value
 * @method string      getPlatform() Returns the current record's "platform" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method mrGame      setName()     Sets the current record's "name" value
 * @method mrGame      setMedium()   Sets the current record's "medium" value
 * @method mrGame      setYear()     Sets the current record's "year" value
 * @method mrGame      setPlatform() Sets the current record's "platform" value
 * @method mrGame      setUserId()   Sets the current record's "user_id" value
 * @method mrGame      setUser()     Sets the current record's "User" value
 * 
 * @package    mediaRepo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BasemrGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mr_game');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('medium', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('platform', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}