<?php

/**
 * BasemrBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $medium
 * @property integer $year
 * @property string $author
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method string      getName()    Returns the current record's "name" value
 * @method string      getMedium()  Returns the current record's "medium" value
 * @method integer     getYear()    Returns the current record's "year" value
 * @method string      getAuthor()  Returns the current record's "author" value
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method mrBook      setName()    Sets the current record's "name" value
 * @method mrBook      setMedium()  Sets the current record's "medium" value
 * @method mrBook      setYear()    Sets the current record's "year" value
 * @method mrBook      setAuthor()  Sets the current record's "author" value
 * @method mrBook      setUserId()  Sets the current record's "user_id" value
 * @method mrBook      setUser()    Sets the current record's "User" value
 * 
 * @package    mediaRepo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BasemrBook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mr_book');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('medium', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}