<?php

/**
 * BasemrMusic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string  getName() Returns the current record's "name" value
 * @method mrMusic setName() Sets the current record's "name" value
 * 
 * @package    mediaRepo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BasemrMusic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mr_music');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}