<?php

/**
 * BasemrBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $author
 * @property sfGuardUser $User
 * 
 * @method string      getAuthor() Returns the current record's "author" value
 * @method sfGuardUser getUser()   Returns the current record's "User" value
 * @method mrBook      setAuthor() Sets the current record's "author" value
 * @method mrBook      setUser()   Sets the current record's "User" value
 * 
 * @package    mediaRepo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BasemrBook extends mrMedia
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mr_book');
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}