<?php

/**
 * mrMusic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaRepo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class mrMusic extends BasemrMusic
{
  public function orderSongs($songs)
  {
    $songs = array_flip($songs);
    
    foreach($this->Songs as $song)
    {
      $song->position = $songs[$song->id] + 1;
      $song->save();
    }
  }
  
  public function getNewSongPosition()
  {
    $song = Doctrine_Query::create()
      ->from('mrSong')
      ->where('album_id = ?', $this->id)
      ->orderBy('position DESC')
      ->fetchOne();
      
    return ($song) ? $song->position + 1 : 1;
  }
}