<?php

/**
 * mrSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaRepo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class mrSong extends BasemrSong
{
	public function preSave($con = null)
	{
		if(!$this->position)
		{
			$this->position = $this->Album->getNewSongPosition();
		}
		
		parent::preSave($con);
	}
}