<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/27 06:19:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=media_repo',
  'username' => 'root',
  'password' => '',
  'name' => 'doctrine',
)),);
