mrBook:
  columns:
    name:     string(255)
    medium:   string(255)
    year:     integer(4)
    author:   string(255)
    hardback: boolean
    user_id:  integer(4)
  relations:
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Books
      onDelete:     cascade