mrGame:
  inheritance:
    type: concrete
    extends: mrMedia
  columns:
    platform: string(255)
  relations:
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Games
      onDelete:     cascade