mrMovie:
  columns:
    name:    string(255)
    medium:  string(255)
    year:    integer(4)
    format:  string(255)
    user_id: integer(4)
  relations:
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Movies
      onDelete:     cascade