mrMusic:
  inheritance:
    type: concrete
    extends: mrMedia
  columns:
    artist:  string(255)
  relations:
    User:
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      foreignAlias: Music
      onDelete:     cascade