mrSong:
  columns:
    name:     string(255)
    album_id: integer(8)
  relations:
    Album:
      class:        mrMusic
      local:        album_id
      foreign:      id
      foreignAlias: Songs
      onDelete:     cascade